#!/bin/ash
set -e

readonly PID_FILE="$APP_HOME"/named.pid

[[ -e "$PID_FILE" ]] && rm -v "$PID_FILE"

# -c: config file
# -f: foreground
exec /usr/sbin/named -c "$APP_CONF_DIR"/named.conf -f -p 53

# vim: set ft=bash ts=2 sts=2 expandtab:

